version: "3"
services:
  cloud-status-checker:
    build: .
    container_name: cloud-status-checker
    restart: always
    networks:
      kuma_macvlan:
        ipv4_address: 10.118.0.153
networks:
  kuma_macvlan:
    external: true
